# fly.toml app configuration file generated for cpex on 2025-02-02T11:41:56+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cpex'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[restart]]
  policy = 'never'

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 8
