# fly.toml app configuration file generated for listen497 on 2025-04-07T12:34:09Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'listen497'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[restart]]
  policy = 'never'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
