app = 'NAME'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[restart]]
  policy = 'never'

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
